//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CognitoPOC.Domain.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CognitoPOC.Domain.Internationalization.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 6-digit code you see in the authenticator app.
        /// </summary>
        public static string CustomTOTPCode {
            get {
                return ResourceManager.GetString("CustomTOTPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Picture.
        /// </summary>
        public static string InvalidPicture {
            get {
                return ResourceManager.GetString("InvalidPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role {Role}.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code. Please try again.
        /// </summary>
        public static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification method was updated successfully.
        /// </summary>
        public static string MfaPreferenceSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("MfaPreferenceSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update your password to continue.
        /// </summary>
        public static string NewPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("NewPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully.
        /// </summary>
        public static string PasswordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code sent to {0}.
        /// </summary>
        public static string PhoneMessageChallengeMessage {
            get {
                return ResourceManager.GetString("PhoneMessageChallengeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number already verified.
        /// </summary>
        public static string PhoneNumberAlreadyVerified {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number was updated successfully.
        /// </summary>
        public static string PhoneNumberUpdated {
            get {
                return ResourceManager.GetString("PhoneNumberUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile not found.
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile updated successfully.
        /// </summary>
        public static string ProfileUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Updated.
        /// </summary>
        public static string RolesUpdated {
            get {
                return ResourceManager.GetString("RolesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to receive the code?.
        /// </summary>
        public static string SelectSignInMfa {
            get {
                return ResourceManager.GetString("SelectSignInMfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 6-digit code sent to the phone {0}.
        /// </summary>
        public static string SendPhoneVerificationTo {
            get {
                return ResourceManager.GetString("SendPhoneVerificationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has timed out for security purposes. Please login again or call us at +1-833-282-2835 for immediate assistance.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 6-digit code you see in the authenticator app.
        /// </summary>
        public static string SetTOTPVerification {
            get {
                return ResourceManager.GetString("SetTOTPVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out successfully.
        /// </summary>
        public static string SignOutSuccessfully {
            get {
                return ResourceManager.GetString("SignOutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator app verified.
        /// </summary>
        public static string SoftwareTokenVerified {
            get {
                return ResourceManager.GetString("SoftwareTokenVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign out.
        /// </summary>
        public static string UnableToSignOut {
            get {
                return ResourceManager.GetString("UnableToSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set up 2-factor verification using an authenticator app verification method.
        /// </summary>
        public static string UnableToStartTOTPVerification {
            get {
                return ResourceManager.GetString("UnableToStartTOTPVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update verification method.
        /// </summary>
        public static string UnableToUpdateMfaPreference {
            get {
                return ResourceManager.GetString("UnableToUpdateMfaPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code. Please try again.
        /// </summary>
        public static string UnableToVerifyPhone {
            get {
                return ResourceManager.GetString("UnableToVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code. Please try again.
        /// </summary>
        public static string UnableToVerifyTOTP {
            get {
                return ResourceManager.GetString("UnableToVerifyTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist.
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is Disabled.
        /// </summary>
        public static string UserIsDisabled {
            get {
                return ResourceManager.GetString("UserIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code was already sent.
        /// </summary>
        public static string VerificationAlreadySent {
            get {
                return ResourceManager.GetString("VerificationAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent instructions to your email to reset your password. If you do not receive the message, please verify that your email is correct, check the spam folder, or resend the message.
        /// </summary>
        public static string VerificationSent {
            get {
                return ResourceManager.GetString("VerificationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak password.
        /// </summary>
        public static string WeakPassword {
            get {
                return ResourceManager.GetString("WeakPassword", resourceCulture);
            }
        }
    }
}
